// src/features/ui-core/header.svelte
<script lang="ts">
	// @ts-ignore
	import logo from '../../assets/general/logo-text.svg?w=512?webp'

	import { slide } from 'svelte/transition'
	import { backInOut } from 'svelte/easing'

	import Hamburger from './hamburger.svelte'
	import Nav from './nav.svelte'
	import Sidebars from './sidebars'

	let currentY: number
	let prevY = 0
	let offset = 500

	let show = true

	$: (() => {
		if (currentY > prevY + offset) {
			prevY = currentY
			show = false
		} else if (currentY < prevY) {
			prevY = currentY
			show = true
		}
	})()

	export let open_header: boolean
</script>

{#if show}
	<Sidebars.Header bind:open={open_header} />

	<header
		class="fixed z-20 lg:flex  px-16 py-6 rounded-b-[30px] bg-primary-600 w-full h-[90px] justify-between items-baseline"
		transition:slide={{ duration: 300, easing: backInOut }}
	>
		<div class="flex justify-between items-center">
			<a href="/" on:click={() => (open_header = false)}>
				<img class="h-[30px] lg:h-[40px] hover:cursor-pointer" srcset={logo} alt="logo" />
			</a>

			<nav class="flex z-30 lg:hidden">
				<Hamburger className="text-white" bind:open={open_header} />
			</nav>
		</div>

		<nav class="text-white font-semibold text-xl hidden lg:flex space-x-16 items-center">
			<Nav />
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="currentColor"
				class="w-6 h-6"
			>
				<path
					fill-rule="evenodd"
					d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z"
					clip-rule="evenodd"
				/>
			</svg>
		</nav>
	</header>
{/if}

<svelte:window bind:scrollY={currentY} />

// components/layout/Header.tsx
'use client'

import { useState, useEffect } from 'react'
import { usePathname } from 'next/navigation'
import Link from 'next/link'
import Image from 'next/image'
import { useSearch } from '@/components/SearchContext'

export function Header() {
  const [isScrolled, setIsScrolled] = useState(false)
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const { openSearch } = useSearch()
  const pathname = usePathname()
  const isHomepage = pathname === '/'

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 100)
    }

    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault()
        openSearch()
      }
    }

    window.addEventListener('scroll', handleScroll)
    window.addEventListener('keydown', handleKeyDown)
    
    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('keydown', handleKeyDown)
    }
  }, [])

  const navigation = [
    { name: 'Learn', path: '/learn' },
    { name: 'Meet', path: '/meet' },
  ]

  return (
    <header className={`fixed z-20 px-8 py-6 w-full transition-transform duration-300 ${!isScrolled ? 'translate-y-0' : '-translate-y-full'}`}>
      <div className="flex justify-between items-start">
        <Link href="/" onClick={() => setIsMenuOpen(false)}>
          <Image
            className="h-[30px] lg:h-[50px] w-auto hover:cursor-pointer"
            src={isHomepage ? "/assets/general/logo-text.png" : "/assets/general/logo-text-dark.png"}
            alt="stAItuned logo"
            width={200}
            height={50}
            priority
          />
        </Link>

        <nav className="fixed right-8 py-3 px-8 text-white rounded-full bg-primary-600 font-semibold text-xl flex space-x-0 lg:space-x-16 items-center">
          <div className="hidden lg:block mr-16">
            <ul className="flex flex-col lg:flex-row py-16 lg:py-0 space-y-8 lg:space-y-0 space-x-0 lg:space-x-16">
              {navigation.map((item) => (
                <li key={item.path}>
                  <Link
                    href={item.path}
                    className={`hover:text-secondary-500 transition ${
                      pathname === item.path ? 'text-secondary-500' : ''
                    }`}
                  >
                    {item.name}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
          
          <div className="rounded-full bg-primary-300 absolute right-0 p-4 cursor-pointer hover:bg-primary-400 transition-colors" onClick={openSearch}>
            <svg className="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
            </svg>
          </div>
          
          <button 
            className="lg:hidden text-white pr-12"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
        </nav>
      </div>
    </header>
  )
}
