// src/features/ui-core/button.svelte
<script lang="ts">
	export let variant: 'primary' | 'secondary' = 'primary'
	export let rounded: 'lg' | 'full' = 'lg'
	export let width: 'fit' | 'full' = 'fit'
	export let type: 'button' | 'submit' | 'reset' = 'button'
    export let onClick = () => {}
	export let className = ''
</script>

{#if variant === 'primary'}
	<button
		{type}
        on:click={onClick}
		class={`p-4 bg-primary-600 hover:bg-primary-500 active:bg-primary-600 transition w-${width} text-white rounded-${rounded} ` +
			className}
	>
		<span class="font-semibold">
			<slot />
		</span>
	</button>
{:else if variant === 'secondary'}
	<button
		{type}
        on:click={onClick}
		class={`p-4 bg-stayYellow-600 hover:bg-stayYellow-500 active:bg-stayYellow-600 transition w-${width} text-primary-600 rounded-${rounded} ` +
			className}
	>
		<span class="font-semibold">
			<slot />
		</span>
	</button>
{/if}

// components/ui/Button.tsx
import { forwardRef } from 'react'

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: 'primary' | 'secondary'
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = 'primary', className = '', children, ...props }, ref) => {
    const base = 'inline-flex items-center justify-center rounded-full font-semibold transition duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2'
    const variants = {
      primary:
        'bg-primary-400 text-white hover:bg-primary-500 focus:ring-primary-300',
      secondary:
        'border border-white/20 bg-white/5 text-white hover:bg-white/10 focus:ring-white',
    }
    return (
      <button
        ref={ref}
        className={`${base} ${variants[variant]} ${className}`}
        {...props}
      >
        {children}
      </button>
    )
  },
)
Button.displayName = 'Button'
