// components/SearchModal.tsx
'use client'

import { useState, useEffect } from 'react'
import { allPosts } from '@/lib/contentlayer'
import Link from 'next/link'
import Image from 'next/image'
import { useSearch } from '@/components/SearchContext'

export function SearchModal() {
  const { isSearchOpen, closeSearch } = useSearch()
  const [searchTerm, setSearchTerm] = useState('')
  const [filteredArticles, setFilteredArticles] = useState<typeof allPosts>([])

  // Filter articles based on search term
  useEffect(() => {
    if (searchTerm.trim()) {
      const filtered = allPosts.filter((article) =>
        article.published !== false &&
        (article.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
         article.author?.toLowerCase().includes(searchTerm.toLowerCase()) ||
         article.meta?.toLowerCase().includes(searchTerm.toLowerCase()))
      )
      setFilteredArticles(filtered)
    } else {
      setFilteredArticles([])
    }
  }, [searchTerm])

  // Handle escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        closeSearch()
      }
    }

    if (isSearchOpen) {
      document.addEventListener('keydown', handleEscape)
      document.body.style.overflow = 'hidden'
    }

    return () => {
      document.removeEventListener('keydown', handleEscape)
      document.body.style.overflow = 'unset'
    }
  }, [isSearchOpen, closeSearch])

  // Reset search when modal closes
  useEffect(() => {
    if (!isSearchOpen) {
      setSearchTerm('')
      setFilteredArticles([])
    }
  }, [isSearchOpen])

  if (!isSearchOpen) return null

  const formatDate = (dateString?: string) => {
    if (!dateString) return ''
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', { 
      day: '2-digit', 
      month: 'short', 
      year: 'numeric' 
    })
  }

  const getValidImageSrc = (article: (typeof allPosts)[0]) => {
    if (!article.cover) return null
    if (article.cover.startsWith('http://') || article.cover.startsWith('https://')) {
      return article.cover
    }
    if (article.cover.startsWith('/')) {
      return article.cover
    }
    const cleanCover = article.cover.replace(/^\.\//, '')
    return `/content/articles/${article.slug}/${cleanCover}`
  }

  return (
    <div className="fixed inset-0 z-[100] overflow-y-auto">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black bg-opacity-50 transition-opacity"
        onClick={closeSearch}
      />
      
      {/* Modal */}
      <div className="flex min-h-full items-start justify-center p-4 text-center sm:p-0 pt-20">
        <div className="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-2xl">
          <div className="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-lg font-medium leading-6 text-gray-900">
                Search Articles
              </h3>
              <button
                onClick={closeSearch}
                className="rounded-md bg-white text-gray-400 hover:text-gray-500 focus:outline-none"
              >
                <span className="sr-only">Close</span>
                <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>

            {/* Search Input */}
            <div className="relative mb-6">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg className="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </div>
              <input
                type="text"
                className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-primary-500 focus:border-primary-500"
                placeholder="Search by title, author, or content..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                autoFocus
              />
            </div>

            {/* Results */}
            <div className="max-h-96 overflow-y-auto">
              {searchTerm && filteredArticles.length === 0 && (
                <div className="text-center py-8">
                  <p className="text-gray-500">No articles found for &ldquo;{searchTerm}&rdquo;</p>
                </div>
              )}
              
              {filteredArticles.length > 0 && (
                <div className="space-y-3">
                  <p className="text-sm text-gray-500 mb-4">
                    Found {filteredArticles.length} article{filteredArticles.length !== 1 ? 's' : ''}
                  </p>
                  {filteredArticles.map((article) => {
                    const imageSrc = getValidImageSrc(article)
                    return (
                      <Link
                        key={article.slug}
                        href={`/learn/${(article.target || 'general').toLowerCase()}/${article.slug}`}
                        onClick={closeSearch}
                        className="block p-3 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                      >
                        <div className="flex items-start space-x-3">
                          {imageSrc && (
                            <Image
                              src={imageSrc}
                              alt={article.title || ''}
                              width={60}
                              height={40}
                              className="rounded object-cover flex-shrink-0"
                              unoptimized={imageSrc.startsWith('http')}
                            />
                          )}
                          <div className="flex-1 min-w-0">
                            <h4 className="text-sm font-medium text-gray-900 mb-1 line-clamp-2">
                              {article.title}
                            </h4>
                            <p className="text-xs text-gray-500 mb-1">
                              By {article.author} • {formatDate(article.date)}
                            </p>
                            {article.target && (
                              <span className="inline-block bg-primary-100 text-primary-800 text-xs px-2 py-1 rounded">
                                {article.target}
                              </span>
                            )}
                          </div>
                        </div>
                      </Link>
                    )
                  })}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/features/ui-core/search-modal.svelte
<script lang="ts">
	import { page } from '$app/stores'

	import { fly } from 'svelte/transition'

	import type { Article } from '@lib/interfaces'

	import dayjs from 'dayjs'

	import { date, scroll } from '@lib/helpers'
	import Modal from './modal'
	import CloseButton from './close-button.svelte'

	export let isOpen: boolean

	const articles: Article[] = date.sort.mostRecentArticleFirst($page.data.articles)

	let filteredArticles: Article[] = []
	let searchParam = ''

	const handleInput = (e: Event) => {
		const currentTarget: HTMLInputElement = e.target as HTMLInputElement
		searchParam = currentTarget.value
		if (searchParam)
			filteredArticles = articles.filter((article: Article) => {
				return article.metadata.title.toLowerCase().includes(searchParam.toLowerCase())
			})
		else filteredArticles = []
	}

	$: (() => {
		if (!isOpen) {
			scroll.enableScroll()
			searchParam = ''
			filteredArticles = []
		} else scroll.disabledScroll()
	})()
</script>

<Modal.Overlay bind:isOpen />

<Modal.Dialog bind:isOpen>
	<Modal.Content>
		<div class="space-y-8">
			<div class="flex items-center text-slate-500">
				<svg
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="currentColor"
					class="w-6 h-6"
				>
					<path
						fill-rule="evenodd"
						d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z"
						clip-rule="evenodd"
					/>
				</svg>
				<input
					on:input|preventDefault={handleInput}
					name="search"
					placeholder="Search by titles or authors..."
					type="search"
					class="w-full rounded-lg border-0 focus:ring-0 placeholder:font-semibold placeholder:text-slate-400"
				/>
				<CloseButton bind:open={isOpen} />
			</div>
			<h1 class="text-lg font-bold text-slate-400">Articles</h1>
			<div class="space-y-4 max-h-80 overflow-y-scroll">
				{#if filteredArticles.length}
					{#each filteredArticles as article}
						<a
							transition:fly={{ duration: 300, x: 50 }}
							target="_self"
							href="/learn/{article.metadata.target.toLowerCase()}/{article.slug}"
							class="block"
						>
							<div
								class="w-full gap-4 bg-slate-50 hover:bg-sky-50 transition p-4 rounded-lg flex items-center hover:cursor-pointer"
							>
								<img
									src={article.metadata.cover}
									class="hidden lg:block h-20 w-20 object-cover rounded-lg"
									alt=""
								/>
								<div class="space-y-2 w-full">
									<div class="text-sm lg:text-lg">
										<h3 class="font-bold text-slate-700">{article.metadata.title}</h3>
										<p class="text-slate-700">{article.metadata.author}</p>
									</div>
									<p class="text-sm text-slate-400">{article.metadata.meta}</p>
									<div class="hidden lg:flex justify-between text-slate-400">
										<span>{dayjs(article.metadata.date).format('DD MMMM YYYY')}</span>
										<span>{article.metadata.readingTime} min</span>
										<span>{article.metadata.target}</span>
										<span>{article.metadata.language}</span>
									</div>
								</div>
							</div>
						</a>
					{/each}
				{:else}
					<h3 class="text-lg text-slate-400">No articles found</h3>
				{/if}
			</div>
		</div>
	</Modal.Content>
</Modal.Dialog>
