// app/(public)/meet/page.tsx
import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
import { allPosts } from '@/lib/contentlayer'
import { getAuthorData } from '@/lib/authors'
import { PageTransition } from '@/components/ui/PageTransition'

// Force static generation
export const dynamic = 'force-static'
const REVALIDATE_INTERVAL = 60 * 60 // 1 ora in secondi
export const revalidate = REVALIDATE_INTERVAL

export const metadata: Metadata = {
  title: 'Meet Our Writers - stAItuned',
  description: 'Meet the talented writers and AI experts behind stAItuned. Discover our team of passionate authors sharing knowledge about AI and technology.',
  openGraph: {
    title: 'Meet Our Writers - stAItuned',
    description: 'Meet the talented writers and AI experts behind stAItuned.',
    type: 'website',
  },
}

export default async function MeetPage() {
  // Get all unique authors from published posts (our writers)
  const uniqueAuthors = Array.from(new Set(
    allPosts
      .filter(post => post.published !== false && post.author)
      .map(post => post.author!)
  ))

  // Get author data and article counts
  const authorsWithData = await Promise.all(
    uniqueAuthors.map(async (authorName) => {
      const authorData = await getAuthorData(authorName)
      const articleCount = allPosts.filter(
        post => post.author === authorName && post.published !== false
      ).length
      
      return {
        name: authorName,
        slug: authorName.replaceAll(' ', '-'),
        data: authorData,
        articleCount
      }
    })
  )

  // Sort by article count (descending) then by name
  authorsWithData.sort((a, b) => {
    if (b.articleCount !== a.articleCount) {
      return b.articleCount - a.articleCount
    }
    return a.name.localeCompare(b.name)
  })
  return (
    <PageTransition>
      <div className="max-w-7xl mx-auto mb-32 mt-[150px] px-4 space-y-16">
        
        {/* Breadcrumb */}
        <nav className="flex items-center space-x-4 text-primary-500 w-full md:w-fit bg-slate-100 px-8 py-4 rounded-lg font-semibold">
          <Link href="/" className="text-sm lg:text-base opacity-50 hover:underline hover:opacity-100 transition">
            Home
          </Link>
          <span>/</span>
          <span className="text-base lg:text-xl truncate">Meet</span>
        </nav>

        {/* Introduction */}
        <section className="text-primary-600 md:text-lg space-y-8">
          <div className="space-y-2">
            <h3 className="font-bold text-2xl">
              Have you always wanted to exchange opinions about AI practical applications?
            </h3>
            <p>Then you&apos;re in the right place.</p>
          </div>
          <div className="space-y-2">
            <h3 className="font-bold text-2xl">We are stAI tuned</h3>
            <p>
              In January 2022, after years of university spent wishing to find a space for sharing ideas, we wondered if it was the right time for us to create an AI community to share knowledge. As a consequence, stAI tuned was created: an open community in which everyone can share their knowledge, research projects and insights related to the AI topic.
              After the beginning of the project we realized that it’s very common to hear conversations about Artificial Intelligence in many contexts, like work, television, with friends and so on.
            </p>
          </div>
        </section>

        {/* Team Section */}
        <section className="space-y-16">
          <h1 className="text-6xl font-bold text-primary-600 text-center uppercase">Our Writers</h1>
          
          {/* Writers Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {authorsWithData.map((author) => (
              <Link
                key={author.slug}
                href={`/author/${author.slug}`}
                className="group block bg-white rounded-lg shadow-sm hover:shadow-lg transition-all duration-300 p-6 hover:scale-105"
              >
                <div className="flex flex-col items-center text-center space-y-4">
                  <div className="relative">
                    <Image
                      src={`/content/team/${author.slug}/propic.jpg`}
                      alt={author.name}
                      width={100}
                      height={100}
                      className="rounded-full object-cover group-hover:scale-110 transition-transform duration-300"
                    />
                  </div>
                  
                  <div className="space-y-2">
                    <h3 className="font-bold text-lg text-gray-900 group-hover:text-primary-600 transition-colors">
                      {author.data?.name || author.name}
                    </h3>
                    {author.data?.title && (
                      <p className="text-sm text-primary-600 font-medium">
                        {author.data.title}
                      </p>
                    )}
                  </div>
                  
                  {author.data?.description && (
                    <p className="text-xs text-gray-600 line-clamp-3">
                      {author.data.description}
                    </p>
                  )}
                  
                  <div className="bg-primary-100 text-primary-800 text-sm px-3 py-1 rounded-full">
                    {author.articleCount} article{author.articleCount !== 1 ? 's' : ''}
                  </div>
                </div>
              </Link>
            ))}
          </div>
          
          {authorsWithData.length === 0 && (
            <div className="text-center py-12">
              <p className="text-gray-500 text-lg">No writers found.</p>
            </div>
          )}
        </section>
      </div>
    </PageTransition>
  )
}

// src/routes/meet/index.svelte
<script lang="ts">
</script>

<div class="grid grid-cols-1 justify-between"> <!-- generalize! -->
    
    <div class="w-9/12 sm:text-sm md:text-lg  m-auto h-max py-10">
        
        <!-- adjust text ? -->
        <p style="text-color:rgb(26 30 59)"><b>Have you always wanted to exchange opinions about Artificial Intelligence?</b></p>
        <p>You're in the right place then!</p> 
        
        <br />

        <p>
            In January 2022, after years of University spent wishing to find a place
            for sharing ideas, we wondered if it was the right time for us to create our community. <br />
            Hence, stAI tuned was created: a place where everyone can share his own knowledge and research projects. <br /><br />

            Nowadays Artificial Intelligence became a buzzword, and you can hear it wherever you go. <br />
        </p>

        <br />

        <p style="text-color:rgb(26 30 59)"><b>But how many people are really conscious about it?</b></p>
        <p>Our goal is make Artificial Intelligence accessible to anyone!</p>




    </div>


</div>

<section class="items-center ">
    <center>
        <div class="sm:w-6/6 md:w-5/6 lg:w-4/6 bg-primary-500 bg-bgGraph bg-cover bg-center rounded-3xl">
            <img src="assets/mission/Ai logo.svg" alt="logo" class="top-[50px] left-[100px] w-[50vw] max-h-[380px] object-contain  self-end"/>

            <div class="flex flex-col items-end p-10">
                <img
                    class="z-1 w-[500px] text-white  ml-[100px] mt-[200px] mt-0"
                    src="/assets/general/logo-text.svg"
                    alt="logo"
                />
                <p class="text-white text-xl">your sharing spot</p>
            </div>
        </div>
        
    </center>
</section>

<!-- roadmap !! -->

<p class="text-3xl md:text-4xl lg:text-5xl font-bold text-primary-600 uppercase text-center mt-20">Our team</p>

<center>
<section class="mt-20 mb-20 grid sm:grid-cols-1 md:grid-cols-3">
    
        <div class="py-5">
            <div class="team-card shadow-xl">
                <center>
                    <a href="/meet/tech"><div class="button-team sm:text-xl md:text-2xl font-bold text-white">TECH</div></a>
                </center>
            </div>
        </div>

        <div class="py-5">
            <div class="team-card">
                <center><div class="button-team sm:text-xl md:text-2xl font-bold text-white">MARKETING</div></center>
            </div>
        </div>

        <div class="py-5">
            <div class="team-card">
                <center><div class="button-team sm:text-xl md:text-2xl font-bold text-white">WRITERS</div></center>
            </div>
        </div>
</section>
</center>
